version: '3.8'
services:
  client:
    stdin_open: true
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000